### ISSUE TITLE
Why we use Ok everywhere result instead of BadRequest?

### ISSUE THREAD

**Issue by PeterKvayt** [umbraco/Umbraco.Commerce.PaymentProviders.Worldpay#7]
I am not really familiar with Umbraco.Commerce concept of callback processing response statuses flow, but why we return Ok instead BadRequest in following places:

- [Password validation fail](https://github.com/umbraco/Umbraco.Commerce.PaymentProviders.Worldpay/blob/support/10.x/src/Umbraco.Commerce.PaymentProviders.Worldpay/WorldpayBusinessGateway350PaymentProvider.cs#L222)
- [Nothing processed](https://github.com/umbraco/Umbraco.Commerce.PaymentProviders.Worldpay/blob/support/10.x/src/Umbraco.Commerce.PaymentProviders.Worldpay/WorldpayBusinessGateway350PaymentProvider.cs#L249)

@mattbrailsford Could you please anwer me?

**Comment by mattbrailsford** [comment]
We return OK because if these things are wrong, they will always be wrong and so we will never be able to process those requests. 

If we return anything other than an ok, this tells the gateway something went wrong, but please try again, so the gateway will keep asking us to process the request even though we’ve determined the request is not something we can process. So although we can’t do anything about it, we have to return ok to say “we’ve done our best, but we can’t handle this request so don’t bother notifying us again”. 

The only thing we can do is log the exception for manual review and see if the payment can be fixed by a human.

**Comment by PeterKvayt** [comment]
Ok, now I understood, thanks for the reply!
